### ISSUE TITLE
failing at : TASK [polkadot-validator : check if keys already exist]

### ISSUE THREAD

**Issue by StakerSpace** [w3f/polkadot-secure-validator#14]
With ansible it should check if keys are in the keystore of the validator:

fatal: [IP-Address]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'polkadot_network_id' is undefined\n\nThe error appears to be in '/polkadot-secure-validator/ansible/roles/polkadot-validator/tasks/main.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: check if keys already exist\n  ^ here\n"}

**Comment by fgimenez** [comment]
Hey @StakerSpace, thanks for the report!

There have been recent changes in how the existing keys are detected, we now take into account the network id (the default keystore path depends on this). The code is updated to put this value in place in the autogenerated ansible inventory, but it was missing from the inventory sample. I've added it in this PR https://github.com/w3f/polkadot-secure-validator/pull/15 pls update your inventory and give it a try.

Cheers!
