### ISSUE TITLE
Add reserved nodes for public nodes

### ISSUE THREAD

**Issue by StakerSpace** [w3f/polkadot-secure-validator#19]
With more nodes coming online as kusama launch is coming up, the validator node being programmed to only connect to the reserved nodes, the public nodes will serve anybody. Meaning sometimes they close the connection to the validator. I'm on different server providers and with `--reserved-nodes` on the public nodes towards with reserving a slot for the validator it works much more stable. Without this is sometimes even goes down to 1 peer even though 4 are available. 

As more nodes enter the network for a stable validator this is necessar.

**Comment by StakerSpace** [comment]
looks like #22 will solve this.

**Comment by fgimenez** [comment]
> looks like #22 will solve this.

Nope, we still need to specify the VPN multiaddr of the validators as `--reserved-nodes` of the public nodes.

**Comment by StakerSpace** [comment]
Yeah just tested it and --sentry just doesn't solve it
