### ISSUE TITLE
Cannot Finish the main.yml without hanging/freezing

### ISSUE THREAD

**Issue by ilhanu** [w3f/polkadot-secure-validator#48]
I'm a standard user of this tool to upgrade Kusama Nodes. However it's not working for me at the moment when trying to upgrade nodes. 

It freezes and hangs at the following, but not limited to the one below, I'm using additional flags:

```
polkadot_additional_common_flags=''
polkadot_additional_validator_flags=''
```

Starting it with the following command: `ansible-playbook main.yml -i stakerspace.inventory `

This is the message it stays stuck at for longer then 10-15 mins
```
TASK [polkadot-common : cronjob for restarting polkadot service] **************************************************************************************************************************************************
task path: /home/ilhan/dev/polkadot-secure-validator/ansible/roles/polkadot-common/tasks/main.yml:93
skipping: [redacted-IP] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers
```

**Comment by fgimenez** [comment]
Can you please share your inventory? That can help to determine where the problem comes from given that you are using only the ansible roles and the inventory is not created by the tool. 

FWIW the tool used in the proper way (`yarn start` to create first the infrastructure layer with terraform, configure the inventory and later run ansible) world fine here with v0.7.32.

**Comment by ilhanu** [comment]
The inventory file contain 2 validators and 4 sentries. The setup isn't very different than the inventory.sample file in the ansible folder, with some additional flags:

```
[all:vars]
project=w3f
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=15'
polkadot_binary_url='https://github.com/paritytech/polkadot/releases/download/v0.7.32/polkadot'
polkadot_binary_checksum='sha256:c34d63e5d80994b2123a3a0b7c5a81ce8dc0f257ee72064bf06654c2b93e31c9'
polkadot_network_id=ksmcc3
build_dir=/home/ilhan/dev/non-git
polkadot_additional_common_flags=--prometheus-external
polkadot_additional_validator_flags=--telemetry-url 'wss://telemetry-backend.w3f.community/submit 1`
```

I don't use the the terraform part of the tooling, just using the ansible, I left my machine on and in the morning it was updated, so in the end it did work and when it shows the `ran handlers` it's still working I'm just not used to wait that long with this tool.

I agree it works just fine! I rang the alarm too early.
