### ISSUE TITLE
compiling wireguard kernel module failed

### ISSUE THREAD

**Issue by TheGoldenEye** [w3f/polkadot-secure-validator#68]
polkadot-secure-validator installs the headers for the current kernel only
after a kernel update, the wireguard kernel module will be compiled automatically by dkms 
this will fail, if appropriate kernel headers are not installed
the best way, i think, is to install the "linux-headers-generic" package, which always depends on the package with the current kernel headers

**hint:** 
- this is true for kernel older then 5.6 (which includes the wireguard kernel module)
- the lts kernel in ubuntu 20.04 supports wireguard too

**Comment by fgimenez** [comment]
Thanks for the heads up @TheGoldenEye! makes sense, it will be fixed shortly.
