### ISSUE TITLE
Adding a new sentry wg-quick error

### ISSUE THREAD

**Issue by ilhanu** [w3f/polkadot-secure-validator#74]
I have been adding new sentries to my Validator, this happend twice so far with provisioning new different nodes. Setting everything else goes right, but when it's time to start the wg0 service on the new node it gives the following error in the logs of ansible 

`FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control process exited with error code.\nSee \"systemctl status wg-quick@wg0.service\" and \"journalctl -xe\" for details.\n"}`

The output of `systemctl status wg-quick@wg0.service `
```
Jun 17 12:58:21  systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Jun 17 12:58:21  wg-quick[9839]: [#] ip link add wg0 type wireguard
Jun 17 12:58:21  wg-quick[9839]: RTNETLINK answers: Operation not supported
Jun 17 12:58:21  wg-quick[9839]: Unable to access interface: Protocol not supported
Jun 17 12:58:21  wg-quick[9839]: [#] ip link delete dev wg0
Jun 17 12:58:21  wg-quick[9839]: Cannot find device "wg0"
Jun 17 12:58:21  systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Jun 17 12:58:21  systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
```

What worked for me was installing wireguard-dkms and from there on I can manually boot it `wg-quick up wg0` whereas before installing the dkms version it wouldn't

**Comment by fgimenez** [comment]
If I recall correctly there was a problem building the wireguard kernel module for a concrete version of the linux headers that should be fixed with changes landed yesterday, if you don't have an up to date version please try again with the latest version from the tip of master of polkadot-secure-validator

**Comment by ilhanu** [comment]
I was on the latest version/commit that adds the `linux-headers-generic`. I think the latest version is causing this, as I didn't get this until now. Not sure also what the cause is. The above errors are the only things I have, but it got resolved already by the manual steps, just wanted to highlight it as maybe you might have an idea.

**Comment by fgimenez** [comment]
It would be good to try to reproduce, integration tests are passing on GCP with ubuntu 20.04 base images, but we are using the complete workflow, including instances creation.

What kind of images and Linux kernel are you using?
