### ISSUE TITLE
Failing to retrieve node-id

### ISSUE THREAD

**Issue by ilhanu** [w3f/polkadot-secure-validator#9]
I had already a secure-validator-setup, was testing with the latest set-up how it would respond to updates. It get's stuck on polkadot-public task `save log with peer id` when running it with `ansible-playbook main.yml -i /PATH/inventory.sample ` 

It is either is re-trying and fails or gets stuck and doesn't give any log.

As a temporary fix you can free up the journalctl with `journalctl --vacuum-time=2d` and then restart your public-nodes so the node-id line appears when starting your node. The script doesn't get stuck then at this step.

**Comment by fgimenez** [comment]
This is already fixed by getting the public nodes' peerId from the `system_networkState` RPC call, thanks for reporting!
