### ISSUE TITLE
Adding a RestartSec value to systemd template.

### ISSUE THREAD

**Issue by m-saxemberg** [w3f/polkadot-secure-validator#98]
In the systemd template
https://github.com/w3f/polkadot-secure-validator/blob/master/ansible/roles/polkadot-validator/templates/polkadot.service.j2

Wouldn't it make sense to add a RestartSec value like so:
Restart=always
RestartSec=120

Delaying a restart forces the node to look past potentially conflictive votes right after a crash in which the node might not recognise votes because it wasn't able to store the information to the disk.

**Comment by fgimenez** [comment]
@m-saxemberg thanks for the suggestion! makes sense, but maybe just 60s is enough, any reason why you chose 120?

**Comment by m-saxemberg** [comment]
No concrete reason, something we thought was an approximate max range of possible confusing votes.

**Comment by pampatzoglou** [comment]
closed by https://github.com/w3f/polkadot-secure-validator/pull/101
